Adding homepage to master
YoseptF/Smashing-Magazine-Zone-Clone pull request #1
Opened 2019-12-06 22:08 UTC by YoseptF

We finished the 5th project and it was really interesting, we learned a lot about how a website is a design, this was a really insightful project :dancer:

2019-12-06 22:50 UTC, pelzolga123 commented on index.html
> +            <h2 style="display: none;">landing section</h2>
Inline styling should be removed.

2019-12-06 22:50 UTC, pelzolga123 commented on index.html
> +            <h2 style="display: none;">call to action</h2>
Inline styling should be removed.

2019-12-06 22:51 UTC, pelzolga123 commented on index.html
> +        <h2 style="display: none;">lastest section</h2>
Inline styling should be removed.

2019-12-06 22:52 UTC, pelzolga123 requested changes
Project needs more `article` elements and navbar should position elements as original website.

2019-12-06 22:53 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: great!

#### Here are the things you need to change before project can be approved:
* [ ] Navbar should use div and positions elements as at the source page [Link to page](https://www.smashingmagazine.com/) 
That means, you need to look how it's done on original website and add all missing elements inside your navbar `li` elements (content is not important). The same with `div` element, it should contain `nav` like original website.

* [ ] Footer should contain centered links. Right now you have `li` elements, they need to be links. 
* [ ] `callToAction` section should be an `article`.
* [ ] `features fone` div should be an `article`.
* [ ] `episodes ftwo` div should be an `article`.
* [ ] `book` section should be an `article`.
* [ ] `personOfWeek` div should be an `article`.
* [ ] Each `person` div should be an `article`.
* [ ] `tableContent` section should be an `article`.
* [ ] `newsletter five` section should be an `article`.

### Please kindly Fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-09 16:35 UTC, nikasulo approved these changes
# Great job! @YoseptF and @SlowKingV :rocket:.
You may merge your beautiful project :smile: :+1: . See you at the top guys!

2019-12-09 19:07 UTC, merged